import Head from 'next/head'
import Image from 'next/image'
import Navbar from '../components/Navbar'
import Main from '../components/Main'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Frans | Front End Developer</title>
        <meta name='description' content='Generated by create next app' />
      </Head>
      <Navbar />
      <Main />
    </div>
  )
}
