import React from 'react'
import Head from 'next/head'
import Main from '../components/Main'
import Projects from '../components/Projects'
import PreFooter from '../components/PreFooter'

export default function Home() {
  // const [scrollPositionY, setPositionY] = React.useState()

  // React.useEffect(() => {
  //   // fetch("https://raw.githubusercontent.com/fransachmadhw/all-of-my-projects/main/db.json")
  //   // .then(res => res.json())
  //   // .then(data => console.log(data))
  //   function updatePosY() {
  //     setPositionY(window.scrollY)
  //   }
  //   window.addEventListener('scroll', updatePosY)
  //   updatePosY()

  //   return () => window.removeEventListener('scroll', updatePosY)
  // }, [])

  // console.log(scrollPositionY / 1000)

  return (
    <div>
      <Head>
        <title>Frans | Front End Developer</title>
        <meta name='description' content='Generated by create next app' />
      </Head>
      <Main />
      <Projects />
      <PreFooter />
    </div>
  )
}
